package gui;

import data.GameDA;
import java.util.List;
import model.Player;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Arne
 */
public class HighscoreFrame extends javax.swing.JFrame {

    /**
     * Creates new form HigscoreFrame
     */
    
    private static String playername;
    
    public HighscoreFrame(String playername) {
        initComponents();
        getHighscores();
        this.playername = playername;
        //retrieveHighscores();
        btnBack.setVisible(false);
    }
    
    public HighscoreFrame(){
        initComponents();
        getHighscores();
        btnStartGameHighscores.setVisible(false);
        
    }
    
    public void getHighscores(){
    
        List<Player> highscores = GameDA.getInstance().getTop10HighscorePlayers();
        
        int counter = 1;
        for(Player p: highscores){
            
            
            String highscoreRow = "#"+counter+" "+p.getUsername()+": "+p.getHighscore()+"\n";
            txtAreaHighscores.append(highscoreRow);
            
            counter += 1;
        }
        
        
    }
    /*
    private void retrieveHighscores() {                                               
       dataAcces = DataAcces.getInstance();
        try {
            List<Players> players = sql...
            for(Player p : players){
                retrieveArea.append(p.getName + ": " + p.getHighscore);
            }
            
        } catch (SQLException ex) {
            // GameException();
        }
    }
    /*
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAreaHighscores = new javax.swing.JTextArea();
        btnStartGameHighscores = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblHighscoresBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 650));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        txtAreaHighscores.setColumns(20);
        txtAreaHighscores.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtAreaHighscores.setRows(5);
        getContentPane().add(txtAreaHighscores);
        txtAreaHighscores.setBounds(270, 200, 300, 300);

        btnStartGameHighscores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/buttons/start.png"))); // NOI18N
        btnStartGameHighscores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGameHighscoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnStartGameHighscores);
        btnStartGameHighscores.setBounds(600, 520, 160, 50);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(30, 520, 160, 50);

        lblHighscoresBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/backgrounds/highscores-bg.png"))); // NOI18N
        getContentPane().add(lblHighscoresBackground);
        lblHighscoresBackground.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartGameHighscoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGameHighscoresActionPerformed
        new StartGameFrame(playername).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStartGameHighscoresActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new StartFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnStartGameHighscores;
    private javax.swing.JLabel lblHighscoresBackground;
    private javax.swing.JTextArea txtAreaHighscores;
    // End of variables declaration//GEN-END:variables
}
