/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Arne
 */
public class PauseFrame extends javax.swing.JFrame {

    /**
     * Creates new form PauseFrame
     */
    public PauseFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Resume = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblBackgroundPause = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 650));
        setPreferredSize(new java.awt.Dimension(800, 650));
        setSize(new java.awt.Dimension(800, 650));
        getContentPane().setLayout(null);

        Resume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/resume.png"))); // NOI18N
        Resume.setText("Resume");
        Resume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResumeActionPerformed(evt);
            }
        });
        getContentPane().add(Resume);
        Resume.setBounds(330, 230, 160, 50);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/buttons/shop.png"))); // NOI18N
        jButton1.setText("Shop");
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 300, 160, 50);
        jButton1.getAccessibleContext().setAccessibleName("btnShop");

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/exit.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(330, 370, 160, 50);

        lblBackgroundPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backgrounds/game-bg-pause.png"))); // NOI18N
        getContentPane().add(lblBackgroundPause);
        lblBackgroundPause.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResumeActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose(); 
    }//GEN-LAST:event_btnExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Resume;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblBackgroundPause;
    // End of variables declaration//GEN-END:variables
}
