package gui;


import data.GameDA;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Arne
 */
public class ShopFrame extends javax.swing.JFrame {
    private int level = 0;
    List<model.Character> allCharacters;
    private static String playername;
    private int playerId;
    private int charCounter;
    private int charId;
    
    private int selectedCharCounter;
    
    public ShopFrame(String playername) {
        initComponents();
        this.playername = playername;
        playerId = GameDA.getInstance().getPLayerId(this.playername);
        allCharacters = GameDA.getInstance().getShips();
        charCounter = 1;
        charId = 0;
        selectedCharCounter = 0;
        //System.out.println(charCounter);
        showSelectedCharCounter();
        InitCharacters();
        checkBoughtandSelect();
        getGeomsAndCoins();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelUpgrades = new javax.swing.JPanel();
        lblSpeed = new javax.swing.JLabel();
        lblBulletPower = new javax.swing.JLabel();
        lblBulletSpeed = new javax.swing.JLabel();
        lblFireRate = new javax.swing.JLabel();
        lblHitpoints = new javax.swing.JLabel();
        lblSpeedGems = new javax.swing.JLabel();
        lblBulletPowerGems = new javax.swing.JLabel();
        lblBulletSpeedGems = new javax.swing.JLabel();
        lblFireRateGems = new javax.swing.JLabel();
        lblHitPointsGems = new javax.swing.JLabel();
        lblUpgradeBarSpeed = new javax.swing.JLabel();
        lblUpgradeBarFireRate = new javax.swing.JLabel();
        lblUpgradeBarHitpoints = new javax.swing.JLabel();
        lblUpgradeBarBulletPower = new javax.swing.JLabel();
        lblUpgradeBarBulletSpeed = new javax.swing.JLabel();
        lblIconSpeed = new javax.swing.JLabel();
        lblIconSpeed1 = new javax.swing.JLabel();
        lblIconSpeed2 = new javax.swing.JLabel();
        lblIconSpeed3 = new javax.swing.JLabel();
        lblIconSpeed4 = new javax.swing.JLabel();
        lblIconGemsSpeed = new javax.swing.JLabel();
        lblIconGemsBulletSpeed = new javax.swing.JLabel();
        lblIconGemsBulletPower = new javax.swing.JLabel();
        lblIconGemsFireRate = new javax.swing.JLabel();
        lblIconGemsHitpoints = new javax.swing.JLabel();
        btnPlusSpeed = new javax.swing.JButton();
        btnPlusBulletSpeed = new javax.swing.JButton();
        btnPlusFireRate = new javax.swing.JButton();
        btnPlusHitpoints = new javax.swing.JButton();
        btnPlusBulletPower = new javax.swing.JButton();
        jPanelShip = new javax.swing.JPanel();
        lblShipsName = new javax.swing.JLabel();
        lblAfbeeldingSchip = new javax.swing.JLabel();
        btnNextShip = new javax.swing.JButton();
        btnPreviousShip = new javax.swing.JButton();
        btnUpgradeShip = new javax.swing.JButton();
        current_ship = new javax.swing.JLabel();
        current_selected_ship = new javax.swing.JLabel();
        btnShipSelect = new javax.swing.JButton();
        btnShipBuy = new javax.swing.JButton();
        lblPrice = new javax.swing.JLabel();
        jPanelCompanion = new javax.swing.JPanel();
        lblCompanionName = new javax.swing.JLabel();
        lblAfbeeldingBuddy = new javax.swing.JLabel();
        btnNextCompanion = new javax.swing.JButton();
        btnPreviousCompanion = new javax.swing.JButton();
        btnUpgradeCompanion = new javax.swing.JButton();
        jPanelCurrency = new javax.swing.JPanel();
        lblCoins = new javax.swing.JLabel();
        lblContentCoins = new javax.swing.JLabel();
        lblGems = new javax.swing.JLabel();
        lblContentGems = new javax.swing.JLabel();
        btnShip = new javax.swing.JButton();
        btnCompanion = new javax.swing.JButton();
        lblShip = new javax.swing.JLabel();
        lblCompanion = new javax.swing.JLabel();
        btnStartGame = new javax.swing.JButton();
        btnClan = new javax.swing.JButton();
        btnSettings = new javax.swing.JButton();
        btnHighscores = new javax.swing.JButton();
        btnBackUpgrades = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 650));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanelUpgrades.setBackground(new java.awt.Color(0, 102, 0));
        jPanelUpgrades.setMinimumSize(new java.awt.Dimension(660, 350));
        jPanelUpgrades.setPreferredSize(new java.awt.Dimension(660, 350));

        lblSpeed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSpeed.setText("Speed");

        lblBulletPower.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBulletPower.setText("Bullet Power");

        lblBulletSpeed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBulletSpeed.setText("BulletSpeed");

        lblFireRate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFireRate.setText("Fire Rate");

        lblHitpoints.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHitpoints.setText("Hitpoints");

        lblSpeedGems.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSpeedGems.setText("Gems");

        lblBulletPowerGems.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBulletPowerGems.setText("Gems");

        lblBulletSpeedGems.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBulletSpeedGems.setText("Gems");

        lblFireRateGems.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFireRateGems.setText("Gems");

        lblHitPointsGems.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHitPointsGems.setText("Gems");

        lblUpgradeBarSpeed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/onderdelen/upgradeBar/bar-0.png"))); // NOI18N

        lblUpgradeBarFireRate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/onderdelen/upgradeBar/bar-0.png"))); // NOI18N

        lblUpgradeBarHitpoints.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/onderdelen/upgradeBar/bar-0.png"))); // NOI18N

        lblUpgradeBarBulletPower.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/onderdelen/upgradeBar/bar-0.png"))); // NOI18N

        lblUpgradeBarBulletSpeed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/onderdelen/upgradeBar/bar-0.png"))); // NOI18N

        lblIconSpeed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/onderdelen/upgradeIcons/speed.png"))); // NOI18N
        lblIconSpeed.setText("jLabel1");

        lblIconSpeed1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/onderdelen/upgradeIcons/bulletSpeed.png"))); // NOI18N
        lblIconSpeed1.setText("jLabel1");

        lblIconSpeed2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/onderdelen/upgradeIcons/hitpoints.png"))); // NOI18N
        lblIconSpeed2.setText("jLabel1");

        lblIconSpeed3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/onderdelen/upgradeIcons/fireRate.png"))); // NOI18N
        lblIconSpeed3.setText("jLabel1");

        lblIconSpeed4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/onderdelen/upgradeIcons/bulletPower.png"))); // NOI18N
        lblIconSpeed4.setText("jLabel1");

        lblIconGemsSpeed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sprites/geomSprite.png"))); // NOI18N

        lblIconGemsBulletSpeed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sprites/geomSprite.png"))); // NOI18N

        lblIconGemsBulletPower.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sprites/geomSprite.png"))); // NOI18N

        lblIconGemsFireRate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sprites/geomSprite.png"))); // NOI18N

        lblIconGemsHitpoints.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sprites/geomSprite.png"))); // NOI18N

        btnPlusSpeed.setText("+");
        btnPlusSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusSpeedActionPerformed(evt);
            }
        });

        btnPlusBulletSpeed.setText("+");

        btnPlusFireRate.setText("+");

        btnPlusHitpoints.setText("+");
        btnPlusHitpoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusHitpointsActionPerformed(evt);
            }
        });

        btnPlusBulletPower.setText("+");

        javax.swing.GroupLayout jPanelUpgradesLayout = new javax.swing.GroupLayout(jPanelUpgrades);
        jPanelUpgrades.setLayout(jPanelUpgradesLayout);
        jPanelUpgradesLayout.setHorizontalGroup(
            jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUpgradesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIconSpeed1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIconSpeed4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIconSpeed3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIconSpeed2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUpgradesLayout.createSequentialGroup()
                        .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFireRate)
                            .addComponent(lblHitpoints)
                            .addComponent(lblSpeed))
                        .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelUpgradesLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(lblUpgradeBarHitpoints)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPlusHitpoints, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelUpgradesLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(lblUpgradeBarSpeed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPlusSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelUpgradesLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(lblUpgradeBarFireRate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPlusFireRate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelUpgradesLayout.createSequentialGroup()
                        .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelUpgradesLayout.createSequentialGroup()
                                .addComponent(lblBulletSpeed)
                                .addGap(18, 18, 18)
                                .addComponent(lblUpgradeBarBulletSpeed))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelUpgradesLayout.createSequentialGroup()
                                .addComponent(lblBulletPower)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblUpgradeBarBulletPower)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelUpgradesLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnPlusBulletSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelUpgradesLayout.createSequentialGroup()
                                .addComponent(btnPlusBulletPower, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconGemsHitpoints)
                    .addComponent(lblIconGemsFireRate)
                    .addComponent(lblIconGemsBulletSpeed)
                    .addComponent(lblIconGemsBulletPower)
                    .addComponent(lblIconGemsSpeed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFireRateGems)
                    .addComponent(lblHitPointsGems)
                    .addComponent(lblBulletSpeedGems)
                    .addComponent(lblBulletPowerGems)
                    .addComponent(lblSpeedGems))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelUpgradesLayout.setVerticalGroup(
            jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUpgradesLayout.createSequentialGroup()
                .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUpgradeBarSpeed)
                    .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSpeed)
                        .addComponent(lblIconSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPlusSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblSpeedGems)
                        .addComponent(lblIconGemsSpeed)))
                .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUpgradesLayout.createSequentialGroup()
                        .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelUpgradesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpgradesLayout.createSequentialGroup()
                                        .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnPlusBulletSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblIconGemsBulletSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanelUpgradesLayout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(lblBulletPowerGems)))
                                        .addGap(1, 1, 1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblIconSpeed1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblBulletSpeed)))
                                .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpgradesLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblBulletPower)
                                            .addComponent(lblIconSpeed4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(24, 24, 24))
                                    .addGroup(jPanelUpgradesLayout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(lblBulletSpeedGems)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanelUpgradesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(lblUpgradeBarBulletSpeed)
                                .addGap(30, 30, 30)
                                .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblUpgradeBarBulletPower)
                                    .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblIconGemsBulletPower, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnPlusBulletPower, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)))
                        .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblFireRate)
                                .addComponent(lblIconSpeed3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelUpgradesLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnPlusFireRate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelUpgradesLayout.createSequentialGroup()
                                        .addComponent(lblHitPointsGems)
                                        .addGap(8, 8, 8))
                                    .addComponent(lblUpgradeBarFireRate)))))
                    .addGroup(jPanelUpgradesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblIconGemsFireRate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUpgradesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelUpgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblHitpoints)
                                .addComponent(lblIconSpeed2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblUpgradeBarHitpoints)
                            .addComponent(btnPlusHitpoints, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIconGemsHitpoints, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelUpgradesLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblFireRateGems)))
                .addContainerGap())
        );

        getContentPane().add(jPanelUpgrades);
        jPanelUpgrades.setBounds(60, 120, 660, 350);

        jPanelShip.setBackground(new java.awt.Color(0, 102, 0));

        lblShipsName.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblShipsName.setText("Ship's Name");

        lblAfbeeldingSchip.setText("Afbeelding Schip");
        lblAfbeeldingSchip.setOpaque(true);

        btnNextShip.setText(">");
        btnNextShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextShipActionPerformed(evt);
            }
        });

        btnPreviousShip.setText("<");
        btnPreviousShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousShipActionPerformed(evt);
            }
        });

        btnUpgradeShip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/upgrade.png"))); // NOI18N
        btnUpgradeShip.setText("Upgrade");
        btnUpgradeShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpgradeShipActionPerformed(evt);
            }
        });

        current_ship.setText("Current Ship: ");

        current_selected_ship.setText("shipname");

        btnShipSelect.setText("SELECT");
        btnShipSelect.setSize(new java.awt.Dimension(160, 50));
        btnShipSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShipSelectActionPerformed(evt);
            }
        });

        btnShipBuy.setText("BUY");
        btnShipBuy.setSize(new java.awt.Dimension(160, 50));
        btnShipBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShipBuyActionPerformed(evt);
            }
        });

        lblPrice.setText("0");

        javax.swing.GroupLayout jPanelShipLayout = new javax.swing.GroupLayout(jPanelShip);
        jPanelShip.setLayout(jPanelShipLayout);
        jPanelShipLayout.setHorizontalGroup(
            jPanelShipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShipLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelShipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelShipLayout.createSequentialGroup()
                        .addComponent(btnUpgradeShip, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblShipsName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(current_ship)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(current_selected_ship, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelShipLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPreviousShip)
                        .addGap(170, 170, 170)
                        .addComponent(lblAfbeeldingSchip, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(btnNextShip))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelShipLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(btnShipBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnShipSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
        jPanelShipLayout.setVerticalGroup(
            jPanelShipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShipLayout.createSequentialGroup()
                .addGroup(jPanelShipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShipsName)
                    .addComponent(btnUpgradeShip, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(current_ship)
                    .addComponent(current_selected_ship))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelShipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAfbeeldingSchip, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNextShip)
                    .addComponent(btnPreviousShip))
                .addGroup(jPanelShipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelShipLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelShipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnShipSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrice))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShipLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnShipBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        getContentPane().add(jPanelShip);
        jPanelShip.setBounds(60, 120, 660, 350);

        jPanelCompanion.setBackground(new java.awt.Color(0, 102, 0));

        lblCompanionName.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCompanionName.setText("Companion's Name");

        lblAfbeeldingBuddy.setText("Afbeelding Buddy");

        btnNextCompanion.setText(">");

        btnPreviousCompanion.setText("<");

        btnUpgradeCompanion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/upgrade.png"))); // NOI18N
        btnUpgradeCompanion.setText("Upgrade");
        btnUpgradeCompanion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpgradeCompanionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCompanionLayout = new javax.swing.GroupLayout(jPanelCompanion);
        jPanelCompanion.setLayout(jPanelCompanionLayout);
        jPanelCompanionLayout.setHorizontalGroup(
            jPanelCompanionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCompanionLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnUpgradeCompanion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCompanionName, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelCompanionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPreviousCompanion)
                .addGap(18, 18, 18)
                .addComponent(lblAfbeeldingBuddy, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnNextCompanion))
        );
        jPanelCompanionLayout.setVerticalGroup(
            jPanelCompanionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCompanionLayout.createSequentialGroup()
                .addGroup(jPanelCompanionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompanionName)
                    .addComponent(btnUpgradeCompanion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanelCompanionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAfbeeldingBuddy, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNextCompanion)
                    .addComponent(btnPreviousCompanion))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelCompanion);
        jPanelCompanion.setBounds(60, 120, 660, 350);

        jPanelCurrency.setBackground(new java.awt.Color(0, 102, 0));
        jPanelCurrency.setPreferredSize(new java.awt.Dimension(290, 50));

        lblCoins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sprites/coinSprite.png"))); // NOI18N
        lblCoins.setText("C:");

        lblContentCoins.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblContentCoins.setText("10000");

        lblGems.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sprites/geomSprite.png"))); // NOI18N

        lblContentGems.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblContentGems.setText("250");

        javax.swing.GroupLayout jPanelCurrencyLayout = new javax.swing.GroupLayout(jPanelCurrency);
        jPanelCurrency.setLayout(jPanelCurrencyLayout);
        jPanelCurrencyLayout.setHorizontalGroup(
            jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCurrencyLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblCoins, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContentCoins)
                .addGap(34, 34, 34)
                .addComponent(lblGems)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContentGems)
                .addGap(56, 56, 56))
        );
        jPanelCurrencyLayout.setVerticalGroup(
            jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCurrencyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContentGems)
                    .addComponent(lblGems)
                    .addGroup(jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblCoins, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblContentCoins)))
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanelCurrency);
        jPanelCurrency.setBounds(450, 0, 300, 50);

        btnShip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/ship-nonActive.png"))); // NOI18N
        btnShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShipActionPerformed(evt);
            }
        });
        getContentPane().add(btnShip);
        btnShip.setBounds(270, 90, 120, 30);

        btnCompanion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/companion-nonActive.png"))); // NOI18N
        btnCompanion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompanionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCompanion);
        btnCompanion.setBounds(390, 90, 120, 30);

        lblShip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/ship-active.png"))); // NOI18N
        getContentPane().add(lblShip);
        lblShip.setBounds(270, 90, 120, 30);

        lblCompanion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/companion-active.png"))); // NOI18N
        getContentPane().add(lblCompanion);
        lblCompanion.setBounds(390, 90, 120, 30);

        btnStartGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/start.png"))); // NOI18N
        btnStartGame.setText("Start Game");
        btnStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGameActionPerformed(evt);
            }
        });
        getContentPane().add(btnStartGame);
        btnStartGame.setBounds(620, 540, 160, 50);

        btnClan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/clan.png"))); // NOI18N
        btnClan.setText("Clan");
        btnClan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClanActionPerformed(evt);
            }
        });
        getContentPane().add(btnClan);
        btnClan.setBounds(190, 540, 160, 50);

        btnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/settings.png"))); // NOI18N
        btnSettings.setText("jButton1");
        getContentPane().add(btnSettings);
        btnSettings.setBounds(20, 540, 160, 50);

        btnHighscores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/highscores.png"))); // NOI18N
        btnHighscores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHighscoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnHighscores);
        btnHighscores.setBounds(360, 540, 160, 50);

        btnBackUpgrades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/back.png"))); // NOI18N
        btnBackUpgrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackUpgradesActionPerformed(evt);
            }
        });
        getContentPane().add(btnBackUpgrades);
        btnBackUpgrades.setBounds(60, 480, 160, 50);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backgrounds/shop-bg1.png"))); // NOI18N
        lblBackground.setMaximumSize(new java.awt.Dimension(1920, 1080));
        lblBackground.setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 1920, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jPanelCompanion.setVisible(false);
        btnShip.setVisible(false);
        lblCompanion.setVisible(false);
        jPanelUpgrades.setVisible(false);
        btnBackUpgrades.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShipActionPerformed
       jPanelCompanion.setVisible(false);
       jPanelShip.setVisible(true);
       btnShip.setVisible(false);
       lblShip.setVisible(true);
       btnCompanion.setVisible(true);
       lblCompanion.setVisible(false);
    }//GEN-LAST:event_btnShipActionPerformed

    private void btnPlusHitpointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusHitpointsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlusHitpointsActionPerformed

    private void btnPlusSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusSpeedActionPerformed
        ImageIcon icon = new ImageIcon("src/img/onderdelen/upgradeBar/bar-"+(level+1)+".png");
        level++; 
        lblUpgradeBarSpeed.setIcon(icon);
        
        if(level ==5){
            btnPlusSpeed.setEnabled(false);
        }
    }//GEN-LAST:event_btnPlusSpeedActionPerformed

    private void btnCompanionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompanionActionPerformed
       jPanelCompanion.setVisible(true);
       jPanelShip.setVisible(false);
       btnShip.setVisible(true);
       lblShip.setVisible(false);
       btnCompanion.setVisible(false);
       lblCompanion.setVisible(true);
    }//GEN-LAST:event_btnCompanionActionPerformed

    private void btnNextShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextShipActionPerformed
        //lblAfbeeldingSchip.setBackground(Color.yellow);
        
        model.Character nextShip = null;
        if(charId+1 < allCharacters.size()){
        System.out.println(charCounter);
        nextShip = allCharacters.get(charId + 1);
        }
        if(nextShip != null){
            String spritename = nextShip.getSprite();
            
            System.out.println("spritename:"+ spritename+"-");
            lblAfbeeldingSchip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ships/" + spritename+ ".png")));
            lblShipsName.setText(spritename);
            charCounter += 1;
            charId += 1;
            checkBoughtandSelect();
        }    
    }//GEN-LAST:event_btnNextShipActionPerformed

    private void btnPreviousShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousShipActionPerformed
        //lblAfbeeldingSchip.setBackground(Color.CYAN);
        model.Character nextShip = null;
        System.out.println("charid:"+charId);
        if(charId-1 >= 0){
            System.out.println(charCounter);
        nextShip = allCharacters.get(charId-1);
        }
        if(nextShip != null){
            String spritename = nextShip.getSprite();
            lblAfbeeldingSchip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ships/" + spritename+ ".png")));
            lblShipsName.setText(spritename);
            charCounter -= 1;
            charId -=1;
            checkBoughtandSelect();
        }    
    
    }//GEN-LAST:event_btnPreviousShipActionPerformed
    
    private void checkBoughtandSelect(){
        //functie meegeven playerid en char id, ophalen isBought ja nee
        int isBought = GameDA.getInstance().isBought(playerId, charCounter);
        if(isBought == 1){
            // show selectbutton
            btnShipBuy.setVisible(false);
            lblPrice.setVisible(false);
            btnShipSelect.setVisible(true);
        }
        else{
            // show buy button + price
            btnShipSelect.setVisible(false);
            btnShipBuy.setVisible(true);
            lblPrice.setVisible(true);
            //show price
            int shipPrice = allCharacters.get(charId).getPrice();
            
            lblPrice.setText(Integer.toString(shipPrice));
            
            
            
        }
    }
    
    private void getGeomsAndCoins(){
        lblContentCoins.setText(Integer.toString(GameDA.getInstance().getPremiumcoins(playerId)));
        lblContentGems.setText(Integer.toString(GameDA.getInstance().getGeoms(playerId)));
    }
    
    private void btnUpgradeShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpgradeShipActionPerformed
        jPanelUpgrades.setVisible(true);
        btnBackUpgrades.setVisible(true);
        btnUpgradeShip.setVisible(false);
    }//GEN-LAST:event_btnUpgradeShipActionPerformed

    private void btnBackUpgradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackUpgradesActionPerformed
        jPanelUpgrades.setVisible(false);
        btnBackUpgrades.setVisible(false);
        btnUpgradeShip.setVisible(true);
    }//GEN-LAST:event_btnBackUpgradesActionPerformed

    private void btnUpgradeCompanionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpgradeCompanionActionPerformed
        jPanelUpgrades.setVisible(true);
        btnBackUpgrades.setVisible(true);
        btnUpgradeCompanion.setVisible(false);
    }//GEN-LAST:event_btnUpgradeCompanionActionPerformed

    private void btnClanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClanActionPerformed
        JOptionPane.showMessageDialog(null, "This is not implemented yet");
    }//GEN-LAST:event_btnClanActionPerformed

    private void btnStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGameActionPerformed
        new StartGameFrame(playername).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStartGameActionPerformed

    private void btnHighscoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHighscoresActionPerformed
        new HighscoreFrame(playername).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHighscoresActionPerformed

    private void btnShipBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShipBuyActionPerformed
        
        int currentGeoms = GameDA.getInstance().getGeoms(playerId);
        int characterPrice = allCharacters.get(charId).getPrice();
        
        if(currentGeoms>characterPrice){
        //koop character
        GameDA.getInstance().buyCharacter(playerId,charCounter);
        int newBalance = currentGeoms - characterPrice;
        GameDA.getInstance().setNewGeomBalance(newBalance,playerId);
        checkBoughtandSelect();
        getGeomsAndCoins();
        }
        else{
            JOptionPane.showMessageDialog(null, "Not enough geoms");
        }
        
    }//GEN-LAST:event_btnShipBuyActionPerformed

    private void showSelectedCharCounter(){
        
        model.Character firstShip = allCharacters.get(charId);
        String spritename = firstShip.getSprite();
        current_selected_ship.setText(spritename);
    }
    
    private void btnShipSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShipSelectActionPerformed
            //set global variable selected
            
            selectedCharCounter = charId;
            showSelectedCharCounter();
            
    }//GEN-LAST:event_btnShipSelectActionPerformed

    private void InitCharacters(){  
        model.Character firstShip = allCharacters.get(0);
        String spritename = firstShip.getSprite();
        lblAfbeeldingSchip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ships/" + spritename+ ".png")));  
        lblShipsName.setText(spritename);
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShopFrame(playername).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackUpgrades;
    private javax.swing.JButton btnClan;
    private javax.swing.JButton btnCompanion;
    private javax.swing.JButton btnHighscores;
    private javax.swing.JButton btnNextCompanion;
    private javax.swing.JButton btnNextShip;
    private javax.swing.JButton btnPlusBulletPower;
    private javax.swing.JButton btnPlusBulletSpeed;
    private javax.swing.JButton btnPlusFireRate;
    private javax.swing.JButton btnPlusHitpoints;
    private javax.swing.JButton btnPlusSpeed;
    private javax.swing.JButton btnPreviousCompanion;
    private javax.swing.JButton btnPreviousShip;
    private javax.swing.JButton btnSettings;
    private javax.swing.JButton btnShip;
    private javax.swing.JButton btnShipBuy;
    private javax.swing.JButton btnShipSelect;
    private javax.swing.JButton btnStartGame;
    private javax.swing.JButton btnUpgradeCompanion;
    private javax.swing.JButton btnUpgradeShip;
    private javax.swing.JLabel current_selected_ship;
    private javax.swing.JLabel current_ship;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCompanion;
    private javax.swing.JPanel jPanelCurrency;
    private javax.swing.JPanel jPanelShip;
    private javax.swing.JPanel jPanelUpgrades;
    private javax.swing.JLabel lblAfbeeldingBuddy;
    private javax.swing.JLabel lblAfbeeldingSchip;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBulletPower;
    private javax.swing.JLabel lblBulletPowerGems;
    private javax.swing.JLabel lblBulletSpeed;
    private javax.swing.JLabel lblBulletSpeedGems;
    private javax.swing.JLabel lblCoins;
    private javax.swing.JLabel lblCompanion;
    private javax.swing.JLabel lblCompanionName;
    private javax.swing.JLabel lblContentCoins;
    private javax.swing.JLabel lblContentGems;
    private javax.swing.JLabel lblFireRate;
    private javax.swing.JLabel lblFireRateGems;
    private javax.swing.JLabel lblGems;
    private javax.swing.JLabel lblHitPointsGems;
    private javax.swing.JLabel lblHitpoints;
    private javax.swing.JLabel lblIconGemsBulletPower;
    private javax.swing.JLabel lblIconGemsBulletSpeed;
    private javax.swing.JLabel lblIconGemsFireRate;
    private javax.swing.JLabel lblIconGemsHitpoints;
    private javax.swing.JLabel lblIconGemsSpeed;
    private javax.swing.JLabel lblIconSpeed;
    private javax.swing.JLabel lblIconSpeed1;
    private javax.swing.JLabel lblIconSpeed2;
    private javax.swing.JLabel lblIconSpeed3;
    private javax.swing.JLabel lblIconSpeed4;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblShip;
    private javax.swing.JLabel lblShipsName;
    private javax.swing.JLabel lblSpeed;
    private javax.swing.JLabel lblSpeedGems;
    private javax.swing.JLabel lblUpgradeBarBulletPower;
    private javax.swing.JLabel lblUpgradeBarBulletSpeed;
    private javax.swing.JLabel lblUpgradeBarFireRate;
    private javax.swing.JLabel lblUpgradeBarHitpoints;
    private javax.swing.JLabel lblUpgradeBarSpeed;
    // End of variables declaration//GEN-END:variables
}
