package gui;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Arne
 */
public class StartGameFrame extends javax.swing.JFrame {

    /**
     * Creates new form StartGameFrame
     */
    
    private static String playername;
    
    
    public StartGameFrame(String userId) {
        initComponents();
        this.playername = userId;
        //JOptionPane.showMessageDialog(null, "username:"+playername);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GameModePanel = new javax.swing.JPanel();
        btnSinglePlayer = new javax.swing.JButton();
        btnMultiPlayer = new javax.swing.JButton();
        btnShop = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblBackgroundStartGame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 650));
        setSize(new java.awt.Dimension(800, 650));
        getContentPane().setLayout(null);

        GameModePanel.setMinimumSize(new java.awt.Dimension(540, 750));
        GameModePanel.setOpaque(false);
        GameModePanel.setPreferredSize(new java.awt.Dimension(540, 600));

        btnSinglePlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/singlePlayer.png"))); // NOI18N
        btnSinglePlayer.setText("Single Player");

        btnMultiPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/multiplayer.png"))); // NOI18N
        btnMultiPlayer.setText("Multi Player");

        btnShop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/shop.png"))); // NOI18N
        btnShop.setText("Shop");
        btnShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShopActionPerformed(evt);
            }
        });

        jButton1.setText("Exit");
        jButton1.setActionCommand("btnExit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GameModePanelLayout = new javax.swing.GroupLayout(GameModePanel);
        GameModePanel.setLayout(GameModePanelLayout);
        GameModePanelLayout.setHorizontalGroup(
            GameModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameModePanelLayout.createSequentialGroup()
                .addGroup(GameModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(GameModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(GameModePanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnSinglePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GameModePanelLayout.createSequentialGroup()
                            .addGap(92, 92, 92)
                            .addGroup(GameModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnShop, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnMultiPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        GameModePanelLayout.setVerticalGroup(
            GameModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameModePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnSinglePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnMultiPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnShop, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(414, Short.MAX_VALUE))
        );

        getContentPane().add(GameModePanel);
        GameModePanel.setBounds(220, 160, 350, 360);

        lblBackgroundStartGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backgrounds/start-game-bg.png"))); // NOI18N
        getContentPane().add(lblBackgroundStartGame);
        lblBackgroundStartGame.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShopActionPerformed
        new ShopFrame(playername).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnShopActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartGameFrame(playername).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GameModePanel;
    private javax.swing.JButton btnMultiPlayer;
    private javax.swing.JButton btnShop;
    private javax.swing.JButton btnSinglePlayer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblBackgroundStartGame;
    // End of variables declaration//GEN-END:variables
}
