/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Arne
 */
public class ClanFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClanFrame
     */
    public ClanFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblClanName = new javax.swing.JLabel();
        btnMembers = new javax.swing.JButton();
        btnMessageBoard = new javax.swing.JButton();
        btnOptions = new javax.swing.JButton();
        btnClanBack = new javax.swing.JButton();
        btnLeaveClan = new javax.swing.JButton();
        btnFindClan = new javax.swing.JButton();
        lblBackgroundClan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/back.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.setPreferredSize(new java.awt.Dimension(340, 100));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(40, 860, 330, 80);

        jPanel1.setBackground(new java.awt.Color(51, 102, 0));

        lblClanName.setBackground(new java.awt.Color(0, 0, 0));
        lblClanName.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblClanName.setText("Clan Name");

        btnMembers.setText("Members");
        btnMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMembersActionPerformed(evt);
            }
        });

        btnMessageBoard.setText("MessageBoard");
        btnMessageBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMessageBoardActionPerformed(evt);
            }
        });

        btnOptions.setText("Options");
        btnOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionsActionPerformed(evt);
            }
        });

        btnClanBack.setText("Back");
        btnClanBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClanBackActionPerformed(evt);
            }
        });

        btnLeaveClan.setText("Leave Clan");
        btnLeaveClan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveClanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(lblClanName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnClanBack))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMembers, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(btnMessageBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLeaveClan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClanName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClanBack))
                .addGap(58, 58, 58)
                .addComponent(btnMessageBoard)
                .addGap(48, 48, 48)
                .addComponent(btnMembers)
                .addGap(42, 42, 42)
                .addComponent(btnOptions)
                .addGap(36, 36, 36)
                .addComponent(btnLeaveClan)
                .addGap(0, 241, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 210, 430, 560);

        btnFindClan.setText("Find Clan");
        btnFindClan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindClanActionPerformed(evt);
            }
        });
        getContentPane().add(btnFindClan);
        btnFindClan.setBounds(1480, 835, 335, 100);

        lblBackgroundClan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backgrounds/shop-bg.png"))); // NOI18N
        getContentPane().add(lblBackgroundClan);
        lblBackgroundClan.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnFindClanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindClanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindClanActionPerformed

    private void btnMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMembersActionPerformed
        btnClanBack.setVisible(true);
        btnMembers.setVisible(false);
        btnMessageBoard.setVisible(false);
        btnOptions.setVisible(false);
        btnLeaveClan.setVisible(false);
    }//GEN-LAST:event_btnMembersActionPerformed

    private void btnOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionsActionPerformed
        btnClanBack.setVisible(true);
        btnMembers.setVisible(false);
        btnMessageBoard.setVisible(false);
        btnOptions.setVisible(false);
        btnLeaveClan.setVisible(false);
    }//GEN-LAST:event_btnOptionsActionPerformed

    private void btnMessageBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMessageBoardActionPerformed
        btnClanBack.setVisible(true);
        btnMembers.setVisible(false);
        btnMessageBoard.setVisible(false);
        btnOptions.setVisible(false);
        btnLeaveClan.setVisible(false);
    }//GEN-LAST:event_btnMessageBoardActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        btnClanBack.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnClanBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClanBackActionPerformed
        btnClanBack.setVisible(false);
        btnMembers.setVisible(true);
        btnMessageBoard.setVisible(true);
        btnOptions.setVisible(true);
        btnLeaveClan.setVisible(true);
    }//GEN-LAST:event_btnClanBackActionPerformed

    private void btnLeaveClanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveClanActionPerformed
        btnClanBack.setVisible(true);
        btnMembers.setVisible(false);
        btnMessageBoard.setVisible(false);
        btnOptions.setVisible(false);
        btnLeaveClan.setVisible(false);
    }//GEN-LAST:event_btnLeaveClanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClanFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClanBack;
    private javax.swing.JButton btnFindClan;
    private javax.swing.JButton btnLeaveClan;
    private javax.swing.JButton btnMembers;
    private javax.swing.JButton btnMessageBoard;
    private javax.swing.JButton btnOptions;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackgroundClan;
    private javax.swing.JLabel lblClanName;
    // End of variables declaration//GEN-END:variables
}
