/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Arne
 */
public class HighscoreFrame extends javax.swing.JFrame {

    /**
     * Creates new form HigscoreFrame
     */
    public HighscoreFrame() {
        initComponents();
        //retrieveHighscores();
    }
    /*
    private void retrieveHighscores() {                                               
       dataAcces = DataAcces.getInstance();
        try {
            List<Players> players = sql...
            for(Player p : players){
                retrieveArea.append(p.getName + ": " + p.getHighscore);
            }
            
        } catch (SQLException ex) {
            // GameException();
        }
    }
    /*
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAreaHighscores = new javax.swing.JTextArea();
        btnStartGameHighscores = new javax.swing.JButton();
        lblHighscoresBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 650));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        txtAreaHighscores.setColumns(20);
        txtAreaHighscores.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtAreaHighscores.setRows(5);
        txtAreaHighscores.setText("Arne - 3000 pts\n2\n3\n4\n5\n6\n7\n8\n9\n10");
        getContentPane().add(txtAreaHighscores);
        txtAreaHighscores.setBounds(270, 200, 280, 254);

        btnStartGameHighscores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/start.png"))); // NOI18N
        btnStartGameHighscores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGameHighscoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnStartGameHighscores);
        btnStartGameHighscores.setBounds(600, 520, 160, 50);

        lblHighscoresBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backgrounds/highscores-bg.png"))); // NOI18N
        getContentPane().add(lblHighscoresBackground);
        lblHighscoresBackground.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartGameHighscoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGameHighscoresActionPerformed
        new StartGameFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStartGameHighscoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HighscoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HighscoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HighscoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HighscoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HighscoreFrame().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartGameHighscores;
    private javax.swing.JLabel lblHighscoresBackground;
    private javax.swing.JTextArea txtAreaHighscores;
    // End of variables declaration//GEN-END:variables
}
