/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Arne
 */
public class ShopFrame extends javax.swing.JFrame {

    /**
     * Creates new form ShopFrame
     */
    public ShopFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelShip = new javax.swing.JPanel();
        lblShipsName = new javax.swing.JLabel();
        lblAfbeeldingSchip = new javax.swing.JLabel();
        jPanelBuddy = new javax.swing.JPanel();
        lblBuddiesName = new javax.swing.JLabel();
        lblAfbeeldingBuddy = new javax.swing.JLabel();
        jPanelCurrency = new javax.swing.JPanel();
        lblCoins = new javax.swing.JLabel();
        lblContentCoins = new javax.swing.JLabel();
        lblGems = new javax.swing.JLabel();
        lblContentGems = new javax.swing.JLabel();
        lblSpeed = new javax.swing.JLabel();
        lblBulletPower = new javax.swing.JLabel();
        lblBulletSpeed = new javax.swing.JLabel();
        lblFireRate = new javax.swing.JLabel();
        lblHitpoints = new javax.swing.JLabel();
        lblSpeedCoins = new javax.swing.JLabel();
        lblBulletPowerCoins = new javax.swing.JLabel();
        lblBulletSpeedCoins = new javax.swing.JLabel();
        lblFireRateCoins = new javax.swing.JLabel();
        lblHitPointsCoins = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        btnBack.setText("Back");
        getContentPane().add(btnBack);
        btnBack.setBounds(100, 260, 59, 25);

        lblShipsName.setText("Ship's Name");

        lblAfbeeldingSchip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button.jpg"))); // NOI18N
        lblAfbeeldingSchip.setText("Afbeelding Schip");

        javax.swing.GroupLayout jPanelShipLayout = new javax.swing.GroupLayout(jPanelShip);
        jPanelShip.setLayout(jPanelShipLayout);
        jPanelShipLayout.setHorizontalGroup(
            jPanelShipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShipLayout.createSequentialGroup()
                .addGroup(jPanelShipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelShipLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAfbeeldingSchip))
                    .addGroup(jPanelShipLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(lblShipsName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanelShipLayout.setVerticalGroup(
            jPanelShipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShipLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblShipsName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(lblAfbeeldingSchip)
                .addGap(103, 103, 103))
        );

        jTabbedPane1.addTab("Ship", jPanelShip);

        lblBuddiesName.setText("Buddies Name");

        lblAfbeeldingBuddy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button.jpg"))); // NOI18N
        lblAfbeeldingBuddy.setText("Afbeelding Buddy");

        javax.swing.GroupLayout jPanelBuddyLayout = new javax.swing.GroupLayout(jPanelBuddy);
        jPanelBuddy.setLayout(jPanelBuddyLayout);
        jPanelBuddyLayout.setHorizontalGroup(
            jPanelBuddyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuddyLayout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(lblBuddiesName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(jPanelBuddyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBuddyLayout.createSequentialGroup()
                    .addGap(124, 124, 124)
                    .addComponent(lblAfbeeldingBuddy)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelBuddyLayout.setVerticalGroup(
            jPanelBuddyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuddyLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblBuddiesName)
                .addContainerGap(330, Short.MAX_VALUE))
            .addGroup(jPanelBuddyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBuddyLayout.createSequentialGroup()
                    .addGap(203, 203, 203)
                    .addComponent(lblAfbeeldingBuddy)
                    .addContainerGap(64, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Buddy", jPanelBuddy);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(100, 360, 525, 397);

        lblCoins.setText("C:");

        lblContentCoins.setText("10000");

        lblGems.setText("Gems:");

        lblContentGems.setText("250");

        lblSpeed.setText("Speed");

        lblBulletPower.setText("Bullet Power");

        lblBulletSpeed.setText("BulletSpeed");

        lblFireRate.setText("Fire Rate");

        lblHitpoints.setText("Hitpoints");

        lblSpeedCoins.setText("Coins");

        lblBulletPowerCoins.setText("Coins");

        lblBulletSpeedCoins.setText("Coins");

        lblFireRateCoins.setText("Coins");

        lblHitPointsCoins.setText("Coins");

        javax.swing.GroupLayout jPanelCurrencyLayout = new javax.swing.GroupLayout(jPanelCurrency);
        jPanelCurrency.setLayout(jPanelCurrencyLayout);
        jPanelCurrencyLayout.setHorizontalGroup(
            jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCurrencyLayout.createSequentialGroup()
                .addGroup(jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCurrencyLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSpeed)
                            .addComponent(lblBulletPower)
                            .addComponent(lblBulletSpeed)
                            .addComponent(lblFireRate)
                            .addComponent(lblHitpoints))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSpeedCoins)
                            .addComponent(lblBulletPowerCoins)
                            .addComponent(lblBulletSpeedCoins)
                            .addComponent(lblFireRateCoins)
                            .addComponent(lblHitPointsCoins)))
                    .addGroup(jPanelCurrencyLayout.createSequentialGroup()
                        .addContainerGap(46, Short.MAX_VALUE)
                        .addComponent(lblCoins)
                        .addGap(27, 27, 27)
                        .addComponent(lblContentCoins)
                        .addGap(35, 35, 35)
                        .addComponent(lblGems)))
                .addGap(43, 43, 43)
                .addComponent(lblContentGems)
                .addGap(43, 43, 43))
        );
        jPanelCurrencyLayout.setVerticalGroup(
            jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCurrencyLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCoins)
                    .addComponent(lblContentCoins)
                    .addComponent(lblGems)
                    .addComponent(lblContentGems))
                .addGap(65, 65, 65)
                .addGroup(jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCurrencyLayout.createSequentialGroup()
                        .addComponent(lblSpeed)
                        .addGap(44, 44, 44)
                        .addComponent(lblBulletPower)
                        .addGap(64, 64, 64)
                        .addComponent(lblBulletSpeed)
                        .addGap(64, 64, 64)
                        .addComponent(lblFireRate)
                        .addGap(64, 64, 64)
                        .addComponent(lblHitpoints))
                    .addGroup(jPanelCurrencyLayout.createSequentialGroup()
                        .addComponent(lblSpeedCoins)
                        .addGap(54, 54, 54)
                        .addComponent(lblBulletPowerCoins)
                        .addGap(54, 54, 54)
                        .addComponent(lblBulletSpeedCoins)
                        .addGap(64, 64, 64)
                        .addComponent(lblFireRateCoins)
                        .addGap(64, 64, 64)
                        .addComponent(lblHitPointsCoins)))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelCurrency);
        jPanelCurrency.setBounds(1060, 210, 300, 550);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/crazy-scientist.jpg"))); // NOI18N
        lblBackground.setText("Achtergrond");
        lblBackground.setMaximumSize(new java.awt.Dimension(1920, 1080));
        lblBackground.setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShopFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JPanel jPanelBuddy;
    private javax.swing.JPanel jPanelCurrency;
    private javax.swing.JPanel jPanelShip;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAfbeeldingBuddy;
    private javax.swing.JLabel lblAfbeeldingSchip;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBuddiesName;
    private javax.swing.JLabel lblBulletPower;
    private javax.swing.JLabel lblBulletPowerCoins;
    private javax.swing.JLabel lblBulletSpeed;
    private javax.swing.JLabel lblBulletSpeedCoins;
    private javax.swing.JLabel lblCoins;
    private javax.swing.JLabel lblContentCoins;
    private javax.swing.JLabel lblContentGems;
    private javax.swing.JLabel lblFireRate;
    private javax.swing.JLabel lblFireRateCoins;
    private javax.swing.JLabel lblGems;
    private javax.swing.JLabel lblHitPointsCoins;
    private javax.swing.JLabel lblHitpoints;
    private javax.swing.JLabel lblShipsName;
    private javax.swing.JLabel lblSpeed;
    private javax.swing.JLabel lblSpeedCoins;
    // End of variables declaration//GEN-END:variables
}
